"""Immutable public model for adaptive local technology tables."""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from math import isfinite
from types import MappingProxyType
from typing import Any, Mapping, Sequence

from .errors import InvalidSamplingDomainError


class AxisSpacing(str, Enum):
    LINEAR = "linear"
    LOG = "log"


@dataclass(frozen=True)
class AxisDomain:
    """Finite sampling domain for one model input coordinate."""

    name: str
    minimum: float
    maximum: float
    count: int
    spacing: AxisSpacing = AxisSpacing.LINEAR

    def __post_init__(self) -> None:
        if not self.name.strip():
            raise InvalidSamplingDomainError("axis name must be non-empty")
        if not (isfinite(self.minimum) and isfinite(self.maximum)):
            raise InvalidSamplingDomainError(f"axis {self.name!r} bounds must be finite")
        if self.minimum > self.maximum:
            raise InvalidSamplingDomainError(
                f"axis {self.name!r}: minimum exceeds maximum"
            )
        if self.count <= 0:
            raise InvalidSamplingDomainError(f"axis {self.name!r}: count must be positive")
        if self.minimum == self.maximum and self.count != 1:
            raise InvalidSamplingDomainError(
                f"axis {self.name!r}: a fixed coordinate must use count=1"
            )
        if self.spacing is AxisSpacing.LOG and self.minimum <= 0:
            raise InvalidSamplingDomainError(
                f"axis {self.name!r}: logarithmic spacing requires positive bounds"
            )


@dataclass(frozen=True)
class SamplingDomain:
    """Cartesian input domain requested from a continuous model."""

    axes: tuple[AxisDomain, ...]

    def __post_init__(self) -> None:
        if not self.axes:
            raise InvalidSamplingDomainError("sampling domain must contain at least one axis")
        names = [axis.name for axis in self.axes]
        if len(set(names)) != len(names):
            raise InvalidSamplingDomainError("sampling-domain axis names must be unique")

    @property
    def point_count(self) -> int:
        count = 1
        for axis in self.axes:
            count *= axis.count
        return count


@dataclass(frozen=True)
class GenerationPolicy:
    """Controls local table generation and deterministic refinement."""

    max_points: int = 100_000
    batch_size: int = 1024
    reject_non_finite: bool = True
    require_saturation: bool = False

    def __post_init__(self) -> None:
        if self.max_points <= 0:
            raise InvalidSamplingDomainError("max_points must be positive")
        if self.batch_size <= 0:
            raise InvalidSamplingDomainError("batch_size must be positive")


@dataclass(frozen=True)
class ModelEvaluation:
    """One exact evaluation returned by a continuous technology model."""

    coordinates: Mapping[str, float]
    quantities: Mapping[str, float]
    region: str | None = None
    saturated: bool | None = None
    diagnostics: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        object.__setattr__(self, "coordinates", MappingProxyType(dict(self.coordinates)))
        object.__setattr__(self, "quantities", MappingProxyType(dict(self.quantities)))
        object.__setattr__(self, "diagnostics", MappingProxyType(dict(self.diagnostics)))


@dataclass(frozen=True)
class GeneratedPoint:
    """Explicit, inspectable row generated by direct model evaluation."""

    coordinates: Mapping[str, float]
    quantities: Mapping[str, float]
    region: str | None
    saturated: bool | None
    generation_level: int
    source: str
    diagnostics: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        object.__setattr__(self, "coordinates", MappingProxyType(dict(self.coordinates)))
        object.__setattr__(self, "quantities", MappingProxyType(dict(self.quantities)))
        object.__setattr__(self, "diagnostics", MappingProxyType(dict(self.diagnostics)))


@dataclass(frozen=True)
class AdaptiveTable:
    """A temporary local table whose rows are exact model evaluations."""

    points: tuple[GeneratedPoint, ...]
    domain: SamplingDomain
    model_identity: str
    generation_level: int = 0
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        object.__setattr__(self, "metadata", MappingProxyType(dict(self.metadata)))

    def filter_saturated(self) -> "AdaptiveTable":
        return AdaptiveTable(
            points=tuple(point for point in self.points if point.saturated is True),
            domain=self.domain,
            model_identity=self.model_identity,
            generation_level=self.generation_level,
            metadata={**self.metadata, "filter": "saturated"},
        )

    def rows(self) -> tuple[dict[str, Any], ...]:
        result: list[dict[str, Any]] = []
        for point in self.points:
            result.append({
                **point.coordinates,
                **point.quantities,
                "region": point.region,
                "saturated": point.saturated,
                "generation_level": point.generation_level,
                "source": point.source,
            })
        return tuple(result)
