#!/usr/bin/env python3
"""
Train, evaluate, and query SKY130 MOS MLP surrogate models.

Designed for:
    technology/sky130_tt_27c_mlp_smoke.csv
and the later dense dataset generated by:
    technology/characterize_sky130_mlp_dataset.py

Key features
------------
- Separate NMOS and PMOS models.
- Supports both legacy DC-only and new DC+AC schemas.
- Uses a per-target mask, so missing BSIM quantities do not discard a row.
- Log transforms positive quantities spanning many decades.
- Signed asinh transforms for charges and capacitance-matrix entries.
- Saves model, scalers, transforms, split indices, metrics, and provenance.
- Supports train, evaluate, predict, and inspect commands.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import random
import sys
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset


INPUT_COLUMNS = [
    "length_um",
    "width_um",
    "vgs_abs_v",
    "vds_abs_v",
    "vbs_abs_v",
    "temperature_c",
]

SUPPORTED_TARGETS = [
    "id_abs_a",
    "vdsat_abs_v",
    "vth_abs_v",
    "gm_s",
    "gds_s",
    "gmb_s",
    "qg_c",
    "qd_c",
    "qs_c",
    "qb_c",
    "cgg_f",
    "cgd_f",
    "cgs_f",
    "cgb_f",
    "cdg_f",
    "cdd_f",
    "cds_f",
    "cdb_f",
    "csg_f",
    "csd_f",
    "css_f",
    "csb_f",
    "cbg_f",
    "cbd_f",
    "cbs_f",
    "cbb_f",
]

POSITIVE_TARGETS = {
    "id_abs_a",
    "vdsat_abs_v",
    "vth_abs_v",
    "gm_s",
    "gds_s",
    "gmb_s",
}


@dataclass
class Standardizer:
    mean: list[float]
    scale: list[float]

    @classmethod
    def fit(cls, x: np.ndarray) -> "Standardizer":
        mean = np.nanmean(x, axis=0)
        scale = np.nanstd(x, axis=0)
        scale = np.where(scale < 1e-12, 1.0, scale)
        return cls(mean.tolist(), scale.tolist())

    def transform(self, x: np.ndarray) -> np.ndarray:
        return (
            (x - np.asarray(self.mean, dtype=np.float64))
            / np.asarray(self.scale, dtype=np.float64)
        )

    def inverse(self, z: np.ndarray) -> np.ndarray:
        return (
            z * np.asarray(self.scale, dtype=np.float64)
            + np.asarray(self.mean, dtype=np.float64)
        )


@dataclass
class TargetTransform:
    kind: str
    reference: float
    mean: float
    scale: float

    @classmethod
    def fit(cls, name: str, values: np.ndarray) -> "TargetTransform":
        finite = np.asarray(values, dtype=np.float64)
        finite = finite[np.isfinite(finite)]
        if finite.size == 0:
            raise ValueError(f"No finite values for target {name}")

        if name in POSITIVE_TARGETS:
            magnitude = np.abs(finite)
            nonzero = magnitude[magnitude > 0]
            floor = (
                max(float(np.quantile(nonzero, 0.001)) * 0.01, 1e-30)
                if nonzero.size
                else 1e-30
            )
            transformed = np.log10(np.maximum(magnitude, floor))
            kind = "log10_positive"
            reference = floor
        else:
            nonzero = np.abs(finite[np.abs(finite) > 0])
            reference = max(
                float(np.median(nonzero)) if nonzero.size else 1e-30,
                1e-30,
            )
            transformed = np.arcsinh(finite / reference)
            kind = "asinh_signed"

        mean = float(np.mean(transformed))
        scale = float(np.std(transformed))
        if scale < 1e-12:
            scale = 1.0
        return cls(kind, reference, mean, scale)

    def transform(self, values: np.ndarray) -> np.ndarray:
        values = np.asarray(values, dtype=np.float64)
        if self.kind == "log10_positive":
            raw = np.log10(np.maximum(np.abs(values), self.reference))
        elif self.kind == "asinh_signed":
            raw = np.arcsinh(values / self.reference)
        else:
            raise ValueError(f"Unknown transform: {self.kind}")
        return (raw - self.mean) / self.scale

    def inverse(self, values: np.ndarray) -> np.ndarray:
        raw = values * self.scale + self.mean
        if self.kind == "log10_positive":
            return np.power(10.0, raw)
        if self.kind == "asinh_signed":
            return np.sinh(raw) * self.reference
        raise ValueError(f"Unknown transform: {self.kind}")


class MosMLP(nn.Module):
    def __init__(
        self,
        input_dim: int,
        output_dim: int,
        hidden_dims: list[int],
        activation: str,
        dropout: float,
    ) -> None:
        super().__init__()
        activation_map: dict[str, type[nn.Module]] = {
            "relu": nn.ReLU,
            "gelu": nn.GELU,
            "silu": nn.SiLU,
            "tanh": nn.Tanh,
        }
        if activation not in activation_map:
            raise ValueError(f"Unsupported activation: {activation}")

        layers: list[nn.Module] = []
        previous = input_dim
        for width in hidden_dims:
            layers.append(nn.Linear(previous, width))
            layers.append(activation_map[activation]())
            if dropout > 0:
                layers.append(nn.Dropout(dropout))
            previous = width
        layers.append(nn.Linear(previous, output_dim))
        self.network = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.network(x)


def parse_hidden_dims(text: str) -> list[int]:
    result = [int(item.strip()) for item in text.split(",") if item.strip()]
    if not result or any(value <= 0 for value in result):
        raise argparse.ArgumentTypeError("hidden dimensions must be positive")
    return result


def parse_targets(text: str | None) -> list[str] | None:
    if not text:
        return None
    return [item.strip() for item in text.split(",") if item.strip()]


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def select_device(name: str) -> torch.device:
    if name == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    return torch.device(name)


def load_dataset(path: Path, polarity: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    required = {"polarity", *INPUT_COLUMNS}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Missing required columns: {sorted(missing)}")

    df = df[df["polarity"].str.lower() == polarity.lower()].copy()
    if "simulation_valid" in df.columns:
        # With --allow-missing-metrics, a successful row may be marked valid
        # even when individual target fields are NaN.
        df = df[df["simulation_valid"].fillna(0).astype(int) == 1].copy()

    for column in INPUT_COLUMNS:
        df[column] = pd.to_numeric(df[column], errors="coerce")
    df = df.dropna(subset=INPUT_COLUMNS)

    if df.empty:
        raise ValueError(f"No usable {polarity} rows")
    return df.reset_index(drop=True)


def choose_targets(df: pd.DataFrame, requested: list[str] | None) -> list[str]:
    candidates = requested or [name for name in SUPPORTED_TARGETS if name in df.columns]
    missing = [name for name in candidates if name not in df.columns]
    if missing:
        raise ValueError(f"Requested targets not present: {missing}")

    result: list[str] = []
    for name in candidates:
        values = pd.to_numeric(df[name], errors="coerce")
        finite_count = int(np.isfinite(values.to_numpy(dtype=np.float64)).sum())
        if finite_count >= 10:
            result.append(name)
        else:
            print(
                f"[WARN] excluding {name}: only {finite_count} finite rows",
                file=sys.stderr,
            )
    if not result:
        raise ValueError("No trainable targets found")
    return result


def make_splits(
    row_count: int,
    seed: int,
    validation_fraction: float,
    test_fraction: float,
) -> dict[str, np.ndarray]:
    if validation_fraction <= 0 or test_fraction <= 0:
        raise ValueError("validation and test fractions must be positive")
    if validation_fraction + test_fraction >= 0.5:
        raise ValueError("validation + test fraction must be below 0.5")

    rng = np.random.default_rng(seed)
    order = rng.permutation(row_count)
    n_test = max(1, int(round(test_fraction * row_count)))
    n_validation = max(1, int(round(validation_fraction * row_count)))
    return {
        "test": order[:n_test],
        "validation": order[n_test:n_test + n_validation],
        "train": order[n_test + n_validation:],
    }


def prepare_data(
    df: pd.DataFrame,
    targets: list[str],
    train_indices: np.ndarray,
) -> tuple[
    np.ndarray,
    np.ndarray,
    np.ndarray,
    Standardizer,
    dict[str, TargetTransform],
]:
    x_raw = df[INPUT_COLUMNS].to_numpy(dtype=np.float64)
    input_scaler = Standardizer.fit(x_raw[train_indices])
    x = input_scaler.transform(x_raw).astype(np.float32)

    y_raw = np.column_stack(
        [pd.to_numeric(df[name], errors="coerce").to_numpy(dtype=np.float64)
         for name in targets]
    )
    mask = np.isfinite(y_raw).astype(np.float32)
    y = np.zeros_like(y_raw, dtype=np.float32)

    transforms: dict[str, TargetTransform] = {}
    for column, name in enumerate(targets):
        transform = TargetTransform.fit(name, y_raw[train_indices, column])
        transforms[name] = transform
        finite = np.isfinite(y_raw[:, column])
        y[finite, column] = transform.transform(y_raw[finite, column]).astype(np.float32)

    return x, y, mask, input_scaler, transforms


def masked_mse(
    prediction: torch.Tensor,
    target: torch.Tensor,
    mask: torch.Tensor,
) -> torch.Tensor:
    squared = (prediction - target) ** 2
    weighted = squared * mask
    denominator = torch.clamp(mask.sum(), min=1.0)
    return weighted.sum() / denominator


def make_loader(
    x: np.ndarray,
    y: np.ndarray,
    mask: np.ndarray,
    indices: np.ndarray,
    batch_size: int,
    shuffle: bool,
) -> DataLoader:
    dataset = TensorDataset(
        torch.from_numpy(x[indices]),
        torch.from_numpy(y[indices]),
        torch.from_numpy(mask[indices]),
    )
    return DataLoader(
        dataset,
        batch_size=min(batch_size, len(dataset)),
        shuffle=shuffle,
        drop_last=False,
    )


@torch.no_grad()
def normalized_predictions(
    model: nn.Module,
    x: np.ndarray,
    device: torch.device,
    batch_size: int = 8192,
) -> np.ndarray:
    model.eval()
    tensor = torch.from_numpy(x)
    parts = []
    for start in range(0, len(tensor), batch_size):
        parts.append(model(tensor[start:start + batch_size].to(device)).cpu().numpy())
    return np.concatenate(parts, axis=0)


def inverse_predictions(
    normalized: np.ndarray,
    targets: list[str],
    transforms: dict[str, TargetTransform],
) -> np.ndarray:
    result = np.empty_like(normalized, dtype=np.float64)
    for column, name in enumerate(targets):
        result[:, column] = transforms[name].inverse(normalized[:, column])
    return result


def compute_metrics(
    actual: np.ndarray,
    predicted: np.ndarray,
    mask: np.ndarray,
    targets: list[str],
) -> dict[str, dict[str, float | int]]:
    result: dict[str, dict[str, float | int]] = {}
    for column, name in enumerate(targets):
        valid = mask[:, column].astype(bool)
        y = actual[valid, column]
        p = predicted[valid, column]
        if len(y) == 0:
            continue

        error = p - y
        abs_error = np.abs(error)
        scale = max(float(np.quantile(np.abs(y), 0.05)), 1e-30)
        relative = abs_error / np.maximum(np.abs(y), scale)
        ss_res = float(np.sum(error**2))
        ss_tot = float(np.sum((y - np.mean(y))**2))
        r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else math.nan

        result[name] = {
            "count": int(len(y)),
            "mae": float(np.mean(abs_error)),
            "rmse": float(np.sqrt(np.mean(error**2))),
            "median_relative_error": float(np.median(relative)),
            "p95_relative_error": float(np.quantile(relative, 0.95)),
            "r2": float(r2),
        }
    return result


def original_target_matrix(df: pd.DataFrame, targets: list[str]) -> tuple[np.ndarray, np.ndarray]:
    values = np.column_stack(
        [pd.to_numeric(df[name], errors="coerce").to_numpy(dtype=np.float64)
         for name in targets]
    )
    return values, np.isfinite(values).astype(np.float32)


def train_polarity(
    csv_path: Path,
    output_dir: Path,
    polarity: str,
    args: argparse.Namespace,
) -> Path:
    set_seed(args.seed)
    device = select_device(args.device)
    df = load_dataset(csv_path, polarity)
    targets = choose_targets(df, parse_targets(args.targets))
    splits = make_splits(
        len(df),
        args.seed,
        args.validation_fraction,
        args.test_fraction,
    )

    x, y, mask, input_scaler, transforms = prepare_data(
        df, targets, splits["train"]
    )

    train_loader = make_loader(
        x, y, mask, splits["train"], args.batch_size, True
    )
    validation_loader = make_loader(
        x, y, mask, splits["validation"], args.batch_size, False
    )

    model = MosMLP(
        input_dim=len(INPUT_COLUMNS),
        output_dim=len(targets),
        hidden_dims=args.hidden_dims,
        activation=args.activation,
        dropout=args.dropout,
    ).to(device)

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=args.learning_rate,
        weight_decay=args.weight_decay,
    )
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="min",
        factor=0.5,
        patience=max(5, args.patience // 5),
        min_lr=1e-6,
    )

    best_validation = math.inf
    best_state: dict[str, torch.Tensor] | None = None
    best_epoch = 0
    stale_epochs = 0
    history: list[dict[str, float | int]] = []

    print(f"\n===== {polarity.upper()} TRAINING =====")
    print(f"device:          {device}")
    print(f"rows:            {len(df):,}")
    print(f"train/val/test:  {len(splits['train'])}/{len(splits['validation'])}/{len(splits['test'])}")
    print(f"targets ({len(targets)}): {targets}")
    print(f"architecture:    {len(INPUT_COLUMNS)} -> {args.hidden_dims} -> {len(targets)}")

    for epoch in range(1, args.epochs + 1):
        model.train()
        train_loss_sum = 0.0
        train_batches = 0

        for xb, yb, mb in train_loader:
            xb = xb.to(device)
            yb = yb.to(device)
            mb = mb.to(device)

            optimizer.zero_grad(set_to_none=True)
            prediction = model(xb)
            loss = masked_mse(prediction, yb, mb)
            if not torch.isfinite(loss):
                raise RuntimeError(f"Non-finite training loss at epoch {epoch}")
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
            optimizer.step()

            train_loss_sum += float(loss.item())
            train_batches += 1

        model.eval()
        validation_loss_sum = 0.0
        validation_batches = 0
        with torch.no_grad():
            for xb, yb, mb in validation_loader:
                loss = masked_mse(
                    model(xb.to(device)),
                    yb.to(device),
                    mb.to(device),
                )
                validation_loss_sum += float(loss.item())
                validation_batches += 1

        train_loss = train_loss_sum / max(train_batches, 1)
        validation_loss = validation_loss_sum / max(validation_batches, 1)
        scheduler.step(validation_loss)
        lr = float(optimizer.param_groups[0]["lr"])

        history.append({
            "epoch": epoch,
            "train_loss": train_loss,
            "validation_loss": validation_loss,
            "learning_rate": lr,
        })

        improved = validation_loss < best_validation - args.min_delta
        if improved:
            best_validation = validation_loss
            best_epoch = epoch
            stale_epochs = 0
            best_state = {
                key: value.detach().cpu().clone()
                for key, value in model.state_dict().items()
            }
        else:
            stale_epochs += 1

        if epoch == 1 or epoch % args.report_every == 0 or improved:
            print(
                f"epoch={epoch:4d} "
                f"train={train_loss:.6f} "
                f"val={validation_loss:.6f} "
                f"lr={lr:.3e}"
            )

        if stale_epochs >= args.patience:
            print(f"[INFO] early stopping at epoch {epoch}")
            break

    if best_state is None:
        raise RuntimeError("Training produced no valid checkpoint")
    model.load_state_dict(best_state)
    model.to(device)

    predicted_normalized = normalized_predictions(model, x, device)
    predicted = inverse_predictions(predicted_normalized, targets, transforms)
    actual, actual_mask = original_target_matrix(df, targets)

    metrics = {}
    for split_name, indices in splits.items():
        metrics[split_name] = compute_metrics(
            actual[indices],
            predicted[indices],
            actual_mask[indices],
            targets,
        )

    output_dir.mkdir(parents=True, exist_ok=True)
    checkpoint_path = output_dir / f"{polarity}_model.pt"
    report_path = output_dir / f"{polarity}_metrics.json"
    history_path = output_dir / f"{polarity}_history.csv"

    checkpoint = {
        "format_version": 1,
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "polarity": polarity,
        "input_columns": INPUT_COLUMNS,
        "targets": targets,
        "architecture": {
            "hidden_dims": args.hidden_dims,
            "activation": args.activation,
            "dropout": args.dropout,
        },
        "model_state_dict": best_state,
        "input_scaler": asdict(input_scaler),
        "target_transforms": {
            name: asdict(transform) for name, transform in transforms.items()
        },
        "training": {
            "seed": args.seed,
            "best_epoch": best_epoch,
            "best_validation_loss": best_validation,
            "batch_size": args.batch_size,
            "learning_rate": args.learning_rate,
            "weight_decay": args.weight_decay,
            "validation_fraction": args.validation_fraction,
            "test_fraction": args.test_fraction,
        },
        "dataset": {
            "path": str(csv_path.resolve()),
            "sha256": sha256_file(csv_path),
            "rows_for_polarity": len(df),
        },
        "metrics": metrics,
    }
    torch.save(checkpoint, checkpoint_path)
    history_path.write_text(pd.DataFrame(history).to_csv(index=False))
    report_path.write_text(json.dumps({
        "checkpoint": str(checkpoint_path),
        "polarity": polarity,
        "best_epoch": best_epoch,
        "best_validation_loss": best_validation,
        "metrics": metrics,
    }, indent=2) + "\n")

    print(f"[PASS] checkpoint: {checkpoint_path}")
    print(f"[PASS] metrics:    {report_path}")
    print(f"[PASS] history:    {history_path}")
    return checkpoint_path


def load_checkpoint(path: Path, device: torch.device) -> tuple[dict[str, Any], MosMLP]:
    checkpoint = torch.load(path, map_location=device, weights_only=False)
    architecture = checkpoint["architecture"]
    model = MosMLP(
        input_dim=len(checkpoint["input_columns"]),
        output_dim=len(checkpoint["targets"]),
        hidden_dims=list(architecture["hidden_dims"]),
        activation=architecture["activation"],
        dropout=float(architecture["dropout"]),
    )
    model.load_state_dict(checkpoint["model_state_dict"])
    model.to(device)
    model.eval()
    return checkpoint, model


def checkpoint_scaler(checkpoint: dict[str, Any]) -> Standardizer:
    return Standardizer(**checkpoint["input_scaler"])


def checkpoint_transforms(checkpoint: dict[str, Any]) -> dict[str, TargetTransform]:
    return {
        name: TargetTransform(**spec)
        for name, spec in checkpoint["target_transforms"].items()
    }


def evaluate_command(args: argparse.Namespace) -> None:
    device = select_device(args.device)
    checkpoint_path = Path(args.checkpoint)
    checkpoint, model = load_checkpoint(checkpoint_path, device)
    polarity = checkpoint["polarity"]
    targets = checkpoint["targets"]

    df = load_dataset(Path(args.csv), polarity)
    x_raw = df[checkpoint["input_columns"]].to_numpy(dtype=np.float64)
    x = checkpoint_scaler(checkpoint).transform(x_raw).astype(np.float32)
    normalized = normalized_predictions(model, x, device)
    predicted = inverse_predictions(
        normalized, targets, checkpoint_transforms(checkpoint)
    )
    actual, mask = original_target_matrix(df, targets)
    metrics = compute_metrics(actual, predicted, mask, targets)

    print(json.dumps({
        "checkpoint": str(checkpoint_path),
        "csv": str(Path(args.csv)),
        "polarity": polarity,
        "rows": len(df),
        "metrics": metrics,
    }, indent=2))


def predict_command(args: argparse.Namespace) -> None:
    device = select_device(args.device)
    checkpoint, model = load_checkpoint(Path(args.checkpoint), device)
    inputs = np.asarray([[
        args.length_um,
        args.width_um,
        args.vgs_v,
        args.vds_v,
        args.vbs_v,
        args.temperature_c,
    ]], dtype=np.float64)

    scaler = checkpoint_scaler(checkpoint)
    x = scaler.transform(inputs).astype(np.float32)
    normalized = normalized_predictions(model, x, device)
    prediction = inverse_predictions(
        normalized,
        checkpoint["targets"],
        checkpoint_transforms(checkpoint),
    )[0]

    result = {
        "polarity": checkpoint["polarity"],
        "inputs": dict(zip(checkpoint["input_columns"], inputs[0].tolist())),
        "predictions": {
            name: float(value)
            for name, value in zip(checkpoint["targets"], prediction)
        },
    }
    print(json.dumps(result, indent=2))


def inspect_command(args: argparse.Namespace) -> None:
    checkpoint = torch.load(
        Path(args.checkpoint),
        map_location="cpu",
        weights_only=False,
    )
    summary = {
        key: value
        for key, value in checkpoint.items()
        if key != "model_state_dict"
    }
    print(json.dumps(summary, indent=2, default=str))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Train and query SKY130 MOS MLP surrogate models"
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    train = subparsers.add_parser("train")
    train.add_argument("--csv", required=True)
    train.add_argument("--output-dir", required=True)
    train.add_argument(
        "--polarities",
        default="nmos,pmos",
        help="Comma-separated nmos,pmos subset",
    )
    train.add_argument("--targets", help="Optional comma-separated target list")
    train.add_argument(
        "--hidden-dims",
        type=parse_hidden_dims,
        default=[128, 128, 128],
    )
    train.add_argument(
        "--activation",
        choices=("relu", "gelu", "silu", "tanh"),
        default="silu",
    )
    train.add_argument("--dropout", type=float, default=0.0)
    train.add_argument("--epochs", type=int, default=500)
    train.add_argument("--batch-size", type=int, default=256)
    train.add_argument("--learning-rate", type=float, default=1e-3)
    train.add_argument("--weight-decay", type=float, default=1e-6)
    train.add_argument("--patience", type=int, default=60)
    train.add_argument("--min-delta", type=float, default=1e-5)
    train.add_argument("--grad-clip", type=float, default=5.0)
    train.add_argument("--validation-fraction", type=float, default=0.15)
    train.add_argument("--test-fraction", type=float, default=0.15)
    train.add_argument("--seed", type=int, default=7)
    train.add_argument("--report-every", type=int, default=10)
    train.add_argument("--device", default="auto")

    evaluate = subparsers.add_parser("evaluate")
    evaluate.add_argument("--csv", required=True)
    evaluate.add_argument("--checkpoint", required=True)
    evaluate.add_argument("--device", default="auto")

    predict = subparsers.add_parser("predict")
    predict.add_argument("--checkpoint", required=True)
    predict.add_argument("--length-um", type=float, required=True)
    predict.add_argument("--width-um", type=float, required=True)
    predict.add_argument("--vgs-v", type=float, required=True)
    predict.add_argument("--vds-v", type=float, required=True)
    predict.add_argument("--vbs-v", type=float, required=True)
    predict.add_argument("--temperature-c", type=float, default=27.0)
    predict.add_argument("--device", default="auto")

    inspect = subparsers.add_parser("inspect")
    inspect.add_argument("--checkpoint", required=True)

    return parser


def main() -> int:
    args = build_parser().parse_args()

    if args.command == "train":
        csv_path = Path(args.csv)
        output_dir = Path(args.output_dir)
        polarities = [
            item.strip().lower()
            for item in args.polarities.split(",")
            if item.strip()
        ]
        invalid = set(polarities) - {"nmos", "pmos"}
        if invalid:
            raise ValueError(f"Invalid polarities: {sorted(invalid)}")
        for polarity in polarities:
            train_polarity(csv_path, output_dir, polarity, args)
        return 0

    if args.command == "evaluate":
        evaluate_command(args)
        return 0

    if args.command == "predict":
        predict_command(args)
        return 0

    if args.command == "inspect":
        inspect_command(args)
        return 0

    raise RuntimeError(f"Unhandled command: {args.command}")


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("\n[FAIL] interrupted", file=sys.stderr)
        raise SystemExit(130)
